import { type Tutor, type Subject, type Session } from '@/types';

export const subjects: { [key: string]: Subject } = {
  math: { name: 'Math', icon: 'Calculator' },
  science: { name: 'Science', icon: 'FlaskConical' },
  history: { name: 'History', icon: 'ScrollText' },
  english: { name: 'English', icon: 'BookOpen' },
  art: { name: 'Art', icon: 'Palette' },
  music: { name: 'Music', icon: 'Music' },
  cs: { name: 'CompSci', icon: 'Code' },
  economics: { name: 'Economics', icon: 'LineChart' },
  spanish: { name: 'Spanish', icon: 'Languages' },
  geography: { name: 'Geography', icon: 'Globe' },
};

export const tutors: Tutor[] = [
  {
    id: '1',
    name: 'Dr. Evelyn Reed',
    image: 'https://randomuser.me/api/portraits/women/44.jpg',
    bio: 'With a PhD in Mathematics, I specialize in making complex concepts simple and engaging. I have over 10 years of experience in tutoring students of all levels.',
    subjects: [subjects.math],
    hourlyRate: 60,
    rating: 4.9,
    sessionsCompleted: 230,
    availability: {
      '2024-08-15': ['09:00', '11:00', '14:00'],
      '2024-08-16': ['10:00', '13:00'],
      '2024-08-18': ['09:00', '11:00', '12:00', '15:00'],
    },
    reviews: [
      {
        id: 'r1',
        studentName: 'Alice Johnson',
        studentImage: 'https://randomuser.me/api/portraits/women/1.jpg',
        rating: 5,
        comment: 'Dr. Reed is fantastic! My calculus grades have improved dramatically.',
        date: '2024-05-20',
      },
      {
        id: 'r2',
        studentName: 'Bob Williams',
        studentImage: 'https://randomuser.me/api/portraits/men/2.jpg',
        rating: 5,
        comment: 'An amazing tutor. She makes algebra almost fun!',
        date: '2024-04-15',
      },
    ],
  },
  {
    id: '4',
    name: 'Ben Carter',
    image: 'https://randomuser.me/api/portraits/men/45.jpg',
    bio: 'Former lab researcher with a passion for teaching. I break down complex scientific topics into bite-sized, understandable pieces. From biology to chemistry, I can help.',
    subjects: [subjects.science],
    hourlyRate: 55,
    rating: 4.7,
    sessionsCompleted: 180,
    availability: {
      '2024-08-17': ['18:00', '19:00', '20:00'],
      '2024-08-19': ['18:00', '19:00'],
    },
    reviews: [
      {
        id: 'r5',
        studentName: 'Eve Adams',
        studentImage: 'https://randomuser.me/api/portraits/women/5.jpg',
        rating: 4.5,
        comment: 'Really helpful with my chemistry homework. Ben is very knowledgeable.',
        date: '2024-06-25',
      },
    ],
  },
  {
    id: '2',
    name: 'Samuel Chen',
    image: 'https://randomuser.me/api/portraits/men/46.jpg',
    bio: 'I am a passionate historian, dedicated to helping students appreciate the stories of our past. MA in History.',
    subjects: [subjects.history],
    hourlyRate: 45,
    rating: 4.8,
    sessionsCompleted: 150,
    availability: {
      '2024-08-15': ['10:00', '12:00', '15:00'],
      '2024-08-17': ['11:00', '14:00', '16:00'],
      '2024-08-19': ['10:00', '12:00', '15:00'],
    },
    reviews: [
      {
        id: 'r3',
        studentName: 'Charlie Brown',
        studentImage: 'https://randomuser.me/api/portraits/men/3.jpg',
        rating: 5,
        comment: "Sam's enthusiasm for history is contagious! I actually enjoy studying now.",
        date: '2024-06-10',
      },
    ],
  },
  {
    id: '5',
    name: 'Olivia Davis',
    image: 'https://randomuser.me/api/portraits/women/48.jpg',
    bio: 'Literature lover and grammar guru. I help students with everything from essay writing and literary analysis to improving their reading comprehension.',
    subjects: [subjects.english],
    hourlyRate: 50,
    rating: 4.9,
    sessionsCompleted: 120,
    availability: {
      '2024-08-15': ['09:00', '10:00', '11:00'],
      '2024-08-18': ['13:00', '14:00'],
      '2024-08-20': ['09:00', '10:00'],
    },
    reviews: [
      {
        id: 'r6',
        studentName: 'Frank Green',
        studentImage: 'https://randomuser.me/api/portraits/men/6.jpg',
        rating: 5,
        comment: 'Olivia helped me so much with my college application essays. A lifesaver!',
        date: '2024-07-22',
      },
    ],
  },
  {
    id: '3',
    name: 'Isabella Rossi',
    image: 'https://randomuser.me/api/portraits/women/47.jpg',
    bio: 'As a professional artist, I love sharing the creative process. I offer lessons in painting, drawing, and sculpture for all ages.',
    subjects: [subjects.art],
    hourlyRate: 50,
    rating: 5.0,
    sessionsCompleted: 98,
    availability: {
      '2024-08-16': ['13:00', '14:00', '15:00'],
      '2024-08-20': ['11:00', '12:00', '13:00'],
      '2024-08-21': ['13:00', '14:00'],
    },
    reviews: [
      {
        id: 'r4',
        studentName: 'Diana Prince',
        studentImage: 'https://randomuser.me/api/portraits/women/4.jpg',
        rating: 5,
        comment: 'Isabella is an incredible art teacher. So patient and encouraging.',
        date: '2024-05-01',
      },
    ],
  },
  {
    id: '6',
    name: 'Leo Hayes',
    image: 'https://randomuser.me/api/portraits/men/49.jpg',
    bio: 'A lifelong musician with a degree from Berklee College of Music. I teach guitar, piano, and music theory with a focus on creativity and fun.',
    subjects: [subjects.music],
    hourlyRate: 55,
    rating: 5.0,
    sessionsCompleted: 85,
    availability: {
      '2024-08-16': ['16:00', '17:00', '18:00'],
      '2024-08-21': ['15:00', '16:00'],
      '2024-08-22': ['17:00', '18:00', '19:00'],
    },
    reviews: [
       {
        id: 'r7',
        studentName: 'Grace Hall',
        studentImage: 'https://randomuser.me/api/portraits/women/7.jpg',
        rating: 5,
        comment: 'Leo is an amazing guitar teacher! I learned so much in just a few sessions.',
        date: '2024-06-18',
      },
    ],
  },
  {
    id: '7',
    name: 'Chloe Garcia',
    image: 'https://randomuser.me/api/portraits/women/50.jpg',
    bio: 'I make math fun and understandable. My goal is to build confidence in my students. BSc in Applied Mathematics.',
    subjects: [subjects.math],
    hourlyRate: 58,
    rating: 4.8,
    sessionsCompleted: 190,
    availability: {
      '2024-08-15': ['13:00', '15:00'],
      '2024-08-16': ['11:00', '14:00'],
      '2024-08-20': ['10:00', '12:00', '16:00'],
    },
    reviews: [
      {
        id: 'r8',
        studentName: 'Henry Jones',
        studentImage: 'https://randomuser.me/api/portraits/men/8.jpg',
        rating: 5,
        comment: 'Chloe is a great tutor. She explains things very clearly and is very patient.',
        date: '2024-07-11',
      },
    ],
  },
  {
    id: '8',
    name: 'David Rodriguez',
    image: 'https://randomuser.me/api/portraits/men/51.jpg',
    bio: 'Passionate about all things science, from the stars to the smallest particles. Let me help you explore the wonders of the universe.',
    subjects: [subjects.science],
    hourlyRate: 62,
    rating: 4.9,
    sessionsCompleted: 210,
    availability: {
      '2024-08-17': ['10:00', '11:00', '12:00'],
      '2024-08-18': ['14:00', '15:00'],
      '2024-08-22': ['18:00', '19:00'],
    },
    reviews: [
       {
        id: 'r9',
        studentName: 'Ivy Clark',
        studentImage: 'https://randomuser.me/api/portraits/women/9.jpg',
        rating: 5,
        comment: 'David is an excellent physics tutor. He made a difficult subject much easier for me to understand.',
        date: '2024-06-30',
      },
    ],
  },
  {
    id: '9',
    name: 'Liam Wilson',
    image: 'https://randomuser.me/api/portraits/men/52.jpg',
    bio: 'Published author and editor with a love for the English language. I can help with creative writing, grammar, and literary analysis.',
    subjects: [subjects.english],
    hourlyRate: 52,
    rating: 4.8,
    sessionsCompleted: 135,
    availability: {
      '2024-08-16': ['09:00', '10:00'],
      '2024-08-19': ['13:00', '14:00', '15:00'],
      '2024-08-23': ['11:00', '12:00'],
    },
    reviews: [
      {
        id: 'r10',
        studentName: 'Jack King',
        studentImage: 'https://randomuser.me/api/portraits/men/10.jpg',
        rating: 4.5,
        comment: 'Liam is great at helping brainstorm for essays. He really helped me find my voice.',
        date: '2024-07-19',
      },
    ],
  },
  {
    id: '10',
    name: 'Sophia Lee',
    image: 'https://randomuser.me/api/portraits/women/52.jpg',
    bio: 'A historian who believes understanding the past is key to the future. I specialize in world history and cultural studies.',
    subjects: [subjects.history],
    hourlyRate: 48,
    rating: 4.9,
    sessionsCompleted: 165,
    availability: {
      '2024-08-18': ['10:00', '11:00'],
      '2024-08-20': ['14:00', '15:00', '16:00'],
      '2024-08-24': ['10:00', '11:00'],
    },
    reviews: [
       {
        id: 'r11',
        studentName: 'Karen Hill',
        studentImage: 'https://randomuser.me/api/portraits/women/11.jpg',
        rating: 5,
        comment: 'Sophia makes history come alive. Her lessons are always so interesting and engaging.',
        date: '2024-07-02',
      },
    ],
  },
    {
    id: '11',
    name: 'Marcus Johnson',
    image: 'https://randomuser.me/api/portraits/men/53.jpg',
    bio: 'Math whiz with a talent for making numbers click. I help students conquer everything from basic algebra to advanced calculus.',
    subjects: [subjects.math],
    hourlyRate: 62,
    rating: 4.9,
    sessionsCompleted: 215,
    availability: {
      '2024-08-15': ['10:00', '12:00'],
      '2024-08-17': ['11:00', '13:00', '15:00'],
      '2024-08-21': ['10:00', '12:00'],
    },
    reviews: [
      {
        id: 'r12',
        studentName: 'Nancy Drew',
        studentImage: 'https://randomuser.me/api/portraits/women/12.jpg',
        rating: 5,
        comment: 'Marcus is a lifesaver! I finally understand trigonometry thanks to him.',
        date: '2024-07-15',
      },
    ],
  },
  {
    id: '12',
    name: 'Dr. Alistair Croft',
    image: 'https://randomuser.me/api/portraits/men/54.jpg',
    bio: 'History is a story waiting to be told. I help students uncover the fascinating narratives of the past, specializing in ancient civilizations.',
    subjects: [subjects.history],
    hourlyRate: 50,
    rating: 4.8,
    sessionsCompleted: 180,
    availability: {
      '2024-08-16': ['14:00', '16:00'],
      '2024-08-19': ['11:00', '14:00'],
      '2024-08-23': ['14:00', '16:00'],
    },
    reviews: [
      {
        id: 'r13',
        studentName: 'Oliver Twist',
        studentImage: 'https://randomuser.me/api/portraits/men/13.jpg',
        rating: 5,
        comment: 'Dr. Croft makes ancient Rome so interesting! I look forward to our lessons.',
        date: '2024-07-18',
      },
    ],
  },
  {
    id: '13',
    name: 'Clara Oswald',
    image: 'https://randomuser.me/api/portraits/women/55.jpg',
    bio: 'English literature enthusiast, here to help you navigate the world of classic and contemporary novels, poetry, and plays.',
    subjects: [subjects.english],
    hourlyRate: 53,
    rating: 4.9,
    sessionsCompleted: 145,
    availability: {
      '2024-08-18': ['12:00', '13:00'],
      '2024-08-20': ['15:00', '16:00', '17:00'],
      '2024-08-24': ['12:00', '13:00'],
    },
    reviews: [
      {
        id: 'r14',
        studentName: 'Peter Pan',
        studentImage: 'https://randomuser.me/api/portraits/men/14.jpg',
        rating: 5,
        comment: 'Clara is wonderful at analyzing literature. She helped me ace my Shakespeare paper.',
        date: '2024-07-21',
      },
    ],
  },
  {
    id: '14',
    name: 'Dr. Kenji Tanaka',
    image: 'https://randomuser.me/api/portraits/men/56.jpg',
    bio: 'Biologist with a passion for the natural world. I offer tutoring in biology, environmental science, and genetics.',
    subjects: [subjects.science],
    hourlyRate: 65,
    rating: 5.0,
    sessionsCompleted: 240,
    availability: {
      '2024-08-15': ['11:00', '12:00'],
      '2024-08-17': ['10:00', '11:00', '12:00'],
      '2024-08-22': ['13:00', '14:00'],
    },
    reviews: [
      {
        id: 'r15',
        studentName: 'Quinn Fabray',
        studentImage: 'https://randomuser.me/api/portraits/women/15.jpg',
        rating: 5,
        comment: 'Dr. Tanaka is a brilliant biology tutor. His explanations are crystal clear.',
        date: '2024-07-24',
      },
    ],
  },
  {
    id: '15',
    name: 'Fiona Applewood',
    image: 'https://randomuser.me/api/portraits/women/57.jpg',
    bio: 'Classically trained pianist and vocalist. I teach piano, voice, and music composition to students of all skill levels.',
    subjects: [subjects.music],
    hourlyRate: 58,
    rating: 4.9,
    sessionsCompleted: 110,
    availability: {
      '2024-08-16': ['15:00', '16:00'],
      '2024-08-20': ['14:00', '15:00', '16:00'],
      '2024-08-25': ['15:00', '16:00'],
    },
    reviews: [
      {
        id: 'r16',
        studentName: 'Rachel Berry',
        studentImage: 'https://randomuser.me/api/portraits/women/16.jpg',
        rating: 5,
        comment: 'Fiona is an amazing voice coach! She has helped me improve my technique so much.',
        date: '2024-07-25',
      },
    ],
  },
  {
    id: '16',
    name: 'Damien Hirst Jr.',
    image: 'https://randomuser.me/api/portraits/men/58.jpg',
    bio: 'Modern artist specializing in digital art and graphic design. Let\'s bring your creative ideas to life on the screen.',
    subjects: [subjects.art],
    hourlyRate: 52,
    rating: 4.8,
    sessionsCompleted: 105,
    availability: {
      '2024-08-18': ['14:00', '15:00', '16:00'],
      '2024-08-21': ['12:00', '13:00'],
      '2024-08-26': ['14:00', '15:00'],
    },
    reviews: [
      {
        id: 'r17',
        studentName: 'Santana Lopez',
        studentImage: 'https://randomuser.me/api/portraits/women/17.jpg',
        rating: 5,
        comment: 'Damien is a super cool and talented teacher. I learned a lot about Photoshop.',
        date: '2024-07-26',
      },
    ],
  },
    {
    id: '17',
    name: 'Arthur Pendragon',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
    bio: 'Medieval history specialist with a focus on European kingdoms. Let\'s explore castles, knights, and epic battles together.',
    subjects: [subjects.history],
    hourlyRate: 47,
    rating: 4.9,
    sessionsCompleted: 195,
    availability: {
      '2024-08-15': ['13:00', '14:00'],
      '2024-08-18': ['11:00', '12:00', '13:00'],
      '2024-08-22': ['15:00', '16:00'],
    },
    reviews: [
      {
        id: 'r18',
        studentName: 'Tina Cohen-Chang',
        studentImage: 'https://randomuser.me/api/portraits/women/18.jpg',
        rating: 5,
        comment: 'Arthur knows so much about medieval history! His lessons are like a real-life adventure.',
        date: '2024-07-27',
      },
    ],
  },
  {
    id: '18',
    name: 'Morgana Le Fay',
    image: 'https://randomuser.me/api/portraits/women/19.jpg',
    bio: 'Chemistry enthusiast who loves to see the "aha!" moment in my students. I specialize in organic and inorganic chemistry.',
    subjects: [subjects.science],
    hourlyRate: 68,
    rating: 5.0,
    sessionsCompleted: 280,
    availability: {
      '2024-08-16': ['10:00', '11:00'],
      '2024-08-19': ['09:00', '10:00', '11:00'],
      '2024-08-23': ['13:00', '14:00'],
    },
    reviews: [
      {
        id: 'r19',
        studentName: 'Uther Pendragon',
        studentImage: 'https://randomuser.me/api/portraits/men/19.jpg',
        rating: 5,
        comment: 'Morgana is a chemistry wizard! She made a tough subject feel easy.',
        date: '2024-07-28',
      },
    ],
  },
  {
    id: '19',
    name: 'Billy Shakespeare',
    image: 'https://randomuser.me/api/portraits/men/20.jpg',
    bio: 'A lover of words and stories. I provide expert guidance on essay writing, poetry analysis, and public speaking.',
    subjects: [subjects.english],
    hourlyRate: 55,
    rating: 4.9,
    sessionsCompleted: 160,
    availability: {
      '2024-08-17': ['14:00', '15:00', '16:00'],
      '2024-08-20': ['11:00', '12:00'],
      '2024-08-24': ['14:00', '15:00'],
    },
    reviews: [
      {
        id: 'r20',
        studentName: 'Victor Frankenstein',
        studentImage: 'https://randomuser.me/api/portraits/men/21.jpg',
        rating: 5,
        comment: 'Billy\'s feedback on my writing was invaluable. He has a true gift for language.',
        date: '2024-07-29',
      },
    ],
  },
  {
    id: '20',
    name: 'Wolfgang Mozart',
    image: 'https://randomuser.me/api/portraits/men/22.jpg',
    bio: 'Music theory and composition expert. I help students understand the structure of music and create their own masterpieces.',
    subjects: [subjects.music],
    hourlyRate: 60,
    rating: 5.0,
    sessionsCompleted: 130,
    availability: {
      '2024-08-18': ['10:00', '11:00', '12:00'],
      '2024-08-21': ['15:00', '16:00'],
      '2024-08-25': ['10:00', '11:00'],
    },
    reviews: [
      {
        id: 'r21',
        studentName: 'Wendy Darling',
        studentImage: 'https://randomuser.me/api/portraits/women/21.jpg',
        rating: 5,
        comment: 'Wolfgang is a brilliant music theory teacher. I understand harmony so much better now.',
        date: '2024-07-30',
      },
    ],
  },
  {
    id: '21',
    name: 'Ada Lovelace',
    image: 'https://randomuser.me/api/portraits/women/60.jpg',
    bio: 'Software engineer with a knack for teaching programming concepts from the ground up. Python, Java, and C++ expert.',
    subjects: [subjects.cs],
    hourlyRate: 70,
    rating: 4.9,
    sessionsCompleted: 300,
    availability: {
      '2024-08-15': ['18:00', '19:00'],
      '2024-08-16': ['18:00', '19:00', '20:00'],
      '2024-08-20': ['19:00', '20:00'],
    },
    reviews: [
       {
        id: 'r22',
        studentName: 'Kevin Mitnick',
        studentImage: 'https://randomuser.me/api/portraits/men/22.jpg',
        rating: 5,
        comment: 'Ada is a fantastic coding instructor. My skills have improved exponentially.',
        date: '2024-07-28',
      },
    ],
  },
  {
    id: '22',
    name: 'Adam Smith',
    image: 'https://randomuser.me/api/portraits/men/61.jpg',
    bio: 'Economics professor with 15 years of experience. I make micro and macroeconomics accessible and interesting.',
    subjects: [subjects.economics],
    hourlyRate: 65,
    rating: 4.8,
    sessionsCompleted: 250,
    availability: {
      '2024-08-17': ['10:00', '11:00'],
      '2024-08-19': ['10:00', '11:00', '12:00'],
      '2024-08-23': ['14:00', '15:00'],
    },
    reviews: [
       {
        id: 'r23',
        studentName: 'Janet Yellen',
        studentImage: 'https://randomuser.me/api/portraits/women/23.jpg',
        rating: 5,
        comment: 'Professor Smith is a master of his craft. He clarified so many difficult economic theories for me.',
        date: '2024-07-29',
      },
    ],
  },
  {
    id: '23',
    name: 'Sofia Reyes',
    image: 'https://randomuser.me/api/portraits/women/62.jpg',
    bio: 'Native Spanish speaker and certified language instructor. I offer conversational practice and grammar lessons for all levels.',
    subjects: [subjects.spanish],
    hourlyRate: 50,
    rating: 4.9,
    sessionsCompleted: 180,
    availability: {
      '2024-08-18': ['16:00', '17:00'],
      '2024-08-21': ['16:00', '17:00', '18:00'],
      '2024-08-24': ['12:00', '13:00'],
    },
    reviews: [
       {
        id: 'r24',
        studentName: 'John Doe',
        studentImage: 'https://randomuser.me/api/portraits/men/24.jpg',
        rating: 5,
        comment: 'Sofia is an excellent language teacher. My Spanish has improved so much!',
        date: '2024-07-30',
      },
    ],
  },
  {
    id: '24',
    name: 'Marco Polo',
    image: 'https://randomuser.me/api/portraits/men/63.jpg',
    bio: 'An explorer at heart, I bring the world into the classroom. I teach physical, human, and cultural geography.',
    subjects: [subjects.geography],
    hourlyRate: 45,
    rating: 4.7,
    sessionsCompleted: 140,
    availability: {
      '2024-08-20': ['09:00', '10:00'],
      '2024-08-22': ['09:00', '10:00', '11:00'],
      '2024-08-25': ['15:00', '16:00'],
    },
    reviews: [
       {
        id: 'r25',
        studentName: 'Jane Smith',
        studentImage: 'https://randomuser.me/api/portraits/women/25.jpg',
        rating: 4.5,
        comment: 'Marco makes learning about different places so fun and interactive.',
        date: '2024-07-31',
      },
    ],
  },
];

export const studentSessions: Session[] = [
  {
    id: 's1',
    tutor: { id: '2', name: 'Samuel Chen', image: tutors[2].image },
    subject: 'History',
    date: '2024-08-19',
    time: '10:00',
    status: 'upcoming',
  },
  {
    id: 's2',
    tutor: { id: '1', name: 'Dr. Evelyn Reed', image: tutors[0].image },
    subject: 'Math',
    date: '2024-08-22',
    time: '14:00',
    status: 'upcoming',
  },
  {
    id: 's3',
    tutor: { id: '3', name: 'Isabella Rossi', image: tutors[4].image },
    subject: 'Art',
    date: '2024-07-10',
    time: '11:00',
    status: 'completed',
  },
  {
    id: 's4',
    tutor: { id: '4', name: 'Ben Carter', image: tutors[1].image },
    subject: 'Science',
    date: '2024-07-05',
    time: '19:00',
    status: 'completed',
  },
];
